[package]
name = "pith-config-native"
description = "Native configuration implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pith-config = { path = "../../../interfaces/pith-config" }
