[package]
name = "rhi-portals-clocks-mock"
description = "Mock implementation of portals-clocks for testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-clocks = { path = "../../../interfaces/portals-clocks" }
