[package]
name = "pith-filesystem"
description = "Filesystem interfaces"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pith-io = { path = "../pith-io" }
