[package]
name = "rhi-portals-observe-native"
description = "Native observability implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-observe = { path = "../../../interfaces/portals-observe" }
