[package]
name = "rhi-portals-filesystem"
description = "Filesystem interfaces"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-io = { path = "../portals-io" }
