[package]
name = "rhi-portals-config-native"
description = "Native configuration implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-config = { path = "../../../interfaces/portals-config" }
