[package]
name = "rhi-portals-random-mock"
description = "Mock implementation of pith-random for testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-random = { path = "../../../interfaces/portals-random" }
