[package]
name = "rhi-portals-nanoid-native"
description = "Native nanoid implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-nanoid = { path = "../../../interfaces/portals-nanoid" }
nanoid = "0.4"
