[package]
name = "rhi-portals-cache-native"
description = "Native in-memory cache implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhi-portals-cache = { path = "../../../interfaces/portals-cache" }
